version: 2

submodules:
  include: all
  recursive: true

conda:
  environment: .test-conda-env.yml

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-latest"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - method: pip
      path: .
