# Conda env file for the readthedocs build
name: rtd-env-py3
channels:
- conda-forge
- nodefaults
dependencies:
# readthedocs does not yet support Python 3.11
# See e.g. https://readthedocs.org/api/v2/build/18650881.txt
- python=3.10
- numpy
- pocl
- mako
- pyopencl
- islpy
- sphinx-autodoc-typehints
- pynauty
- pip:
  - "git+https://github.com/inducer/pytools.git#egg=pytools"
  - "git+https://github.com/inducer/pymbolic.git#egg=pymbolic"
  - "git+https://github.com/inducer/genpy.git#egg=genpy"
  - "git+https://github.com/kaushikcfd/loopy.git#egg=loopy"
  - "git+https://github.com/HPAC/matchpy.git#egg=matchpy"
  - "opt_einsum"
  - "tabulate"
  - "types-tabulate"
  - "types-pytz"
  - "opentuner"
  - "sphinx-math-dollar"
  - "sphinx-copybutton"
  - "sphinx-book-theme"
