name: "Setup Conda Env, Install feinsum."
description: "Checkout, activate test conda env, and create test-conda-env."
inputs:
  run_in_env:
    required: false
    description: "Bash commands to run inside the environment."
runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3"
        auto-activate-base: false
    - run: |
        conda init bash
        source ~/.bashrc
        conda env create -f .test-conda-env.yml
        conda activate test-conda-env
        pip install .
        ${{ inputs.run_in_env }}
      shell: bash
