name: "Setup Conda Env, Install feinsum"
description: "Checkout, activate test conda env, and create test-conda-env"
runs:
  using: "composite"
  steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3"
        auto-activate-base: false
        activate-environment: test-conda-env
        environment-file: .test-conda-env.yml
    - run: |
        pip install .
        ${{ inputs.run_in_env }}
      shell: bash

